#!/usr/bin/env node
// Register Clawd's DeepSeek Harness (dsh) bridge plugin into the user's dsh
// plugin composition.
//
// Strategy: dsh loads user plugins via Cordis patch overlays. A plugin is a
// normal Cordis module addressed by `name`, which the loader resolves as a
// package specifier, a `file://` URL, or a base-URL-relative path (see
// vendor/loader/src/config/tree.ts). Clawd ships the bridge as a ZERO-DEPENDENCY
// ESM module (hooks/dsh-plugin/index.mjs) that only uses node builtins + fetch,
// so it can be imported directly by `file://` URL without touching node_modules.
//
// This installer:
//   1. Writes a ready-to-use patch overlay `$DSH_HOME/clawd-on-desk.cordis.yml`
//      the user can enable with `dsh web --patch <that file>`.
//   2. Best-effort merges the same `insert` into the user patch layer
//      `$DSH_HOME/cordis.patch.yml` (every profile) so it stays enabled across
//      runs. The merge is idempotent and never clobbers unrelated patches.
//
// DSH HOME = $DSH_HOME, else ~/.dsh. Missing home => skipped (dsh not installed).

const fs = require("fs");
const os = require("os");
const path = require("path");
const { pathToFileURL } = require("url");
const { asarUnpackedPath } = require("./json-utils");

const PLUGIN_DIR_NAME = "dsh-plugin";
const PLUGIN_ENTRY = "index.mjs";
const PLUGIN_ID = "clawd-on-desk";
const PATCH_FILENAME = "clawd-on-desk.cordis.yml";
const PATCH_LAYER = "cordis.patch.yml";
// `dsh web` reads the PROFILE-LEVEL user patch layer
// ($DSH_HOME/profiles/<profile>/cordis.patch.yml), not the global
// $DSH_HOME/cordis.patch.yml. The web surface's profile is named "web".
const DEFAULT_PROFILE = "web";

function resolvePluginDir(baseDir) {
  return path.resolve(baseDir || __dirname, PLUGIN_DIR_NAME);
}

function resolvePluginEntry(baseDir) {
  return path.join(resolvePluginDir(baseDir), PLUGIN_ENTRY);
}

/** file:// URL for the plugin entry — the `name` the loader imports. */
function resolvePluginFileUrl(baseDir) {
  const entry = asarUnpackedPath(resolvePluginEntry(baseDir));
  return pathToFileURL(entry).href;
}

function resolveDshHome(options = {}) {
  if (options.dshHome) return options.dshHome;
  const env = options.env || process.env;
  if (env && env.DSH_HOME) return env.DSH_HOME;
  return path.join(os.homedir(), ".dsh");
}

/**
 * Build the patch overlay body (a list containing our `insert` slice).
 * `name` is a `file://` URL to the plugin entry; single-quoted for YAML safety.
 */
function buildPatchBody(pluginFileUrl) {
  const quoted = JSON.stringify(pluginFileUrl); // double-quoted JSON is valid YAML
  return [
    "# Generated by Clawd on Desk. Do not edit the block between the markers.",
    "# Enable with: dsh web --patch " + path.join("$DSH_HOME", PATCH_FILENAME),
    `- insert:`,
    `    - id: ${PLUGIN_ID}`,
    `      name: ${quoted}`,
    `      config:`,
    `        events: true`,
    `        approval: true`,
    ``,
  ].join("\n");
}

/** Whether the user patch layer already contains our plugin id. */
function layerHasPlugin(text) {
  return typeof text === "string" && text.includes(`id: ${PLUGIN_ID}`);
}

/** Drop YAML comment lines and whitespace, leaving only structure. */
function stripYamlComments(text) {
  return String(text || "")
    .split("\n")
    .filter((line) => !/^\s*#/.test(line))
    .join("\n")
    .trim();
}

/**
 * Merge our insert slice into an existing patch-layer file. A dsh patch layer
 * is a top-level YAML list; a fresh profile layer is `[]` (often under a
 * comment header), so we must REPLACE that empty list, not append a stray
 * `- insert:` after it — `[]\n- insert:…` is not a valid list. Handles:
 *   - empty / comment-only / `[]` → replace with our list
 *   - an existing list          → append our `- insert:` as a new item
 *   - already contains our id   → no-op
 */
function mergeIntoPatchLayer(existingText, pluginFileUrl) {
  if (layerHasPlugin(existingText)) {
    return { text: existingText, changed: false, added: false, updated: false };
  }
  const block = buildPatchBody(pluginFileUrl);
  const stripped = stripYamlComments(existingText);
  if (stripped === "" || stripped === "[]" || stripped === "[ ]" || stripped === "[]\n") {
    // Empty list (legitimately `[]` or comment header + `[]`) — replace it.
    return { text: block, changed: true, added: true, updated: false };
  }
  const trimmed = (existingText || "").trimEnd();
  const text = trimmed.length > 0 ? `${trimmed}\n${block}` : block;
  return { text, changed: true, added: true, updated: false };
}

function writePatchLayer(dshHome, pluginFileUrl, options = {}) {
  const patchPath = options.patchPath || path.join(dshHome, PATCH_LAYER);
  let existing = "";
  try {
    existing = fs.readFileSync(patchPath, "utf8");
  } catch {}
  const merged = mergeIntoPatchLayer(existing, pluginFileUrl);
  if (merged.changed) {
    fs.mkdirSync(path.dirname(patchPath), { recursive: true });
    fs.writeFileSync(patchPath, merged.text, "utf8");
  }
  return { patchPath, changed: merged.changed, added: merged.added, updated: merged.updated };
}

/** Write the PROFILE-level user patch layer dsh actually reads (e.g. web). */
function writeProfilePatchLayer(dshHome, profile, pluginFileUrl) {
  const patchPath = path.join(dshHome, "profiles", profile, PATCH_LAYER);
  return writePatchLayer(dshHome, pluginFileUrl, { patchPath });
}

/**
 * Register the Clawd dsh bridge.
 *
 * @param {object} [options]
 * @param {boolean} [options.silent]   suppress console output
 * @param {string}  [options.dshHome]  override dsh home (for tests)
 * @param {string}  [options.patchPath] override user patch-layer path (for tests)
 * @param {string}  [options.baseDir]  override plugin dir base (for tests)
 * @param {string}  [options.env]      env override (for tests)
 * @returns {{ status: string, added: boolean, updated: boolean, dshHome: string, patchPath: string, pluginFile: string, reason?: string }}
 */
function registerDshBridge(options = {}) {
  const dshHome = resolveDshHome(options);
  const pluginFile = resolvePluginFileUrl(options.baseDir);

  // Skip if the dsh home doesn't exist (dsh not installed). This check runs
  // regardless of whether `dshHome` was passed by a caller, so a stale override
  // pointing at a missing directory still reports `skipped` rather than
  // creating a fresh home. `forceCreate` opts out for callers that own the dir.
  let homeExists = true;
  if (options.forceCreate !== true) {
    try { homeExists = fs.statSync(dshHome).isDirectory(); } catch { homeExists = false; }
  }
  if (!homeExists) {
    if (!options.silent) {
      console.log(`Clawd: ${dshHome} not found — skipping DeepSeek Harness bridge registration`);
    }
    return {
      status: "skipped",
      added: false,
      updated: false,
      dshHome,
      patchPath: path.join(dshHome, PATCH_LAYER),
      pluginFile,
      reason: "dsh-home-not-found",
    };
  }

  // Always write the standalone `--patch` overlay (idempotent).
  const overlayPath = path.join(dshHome, PATCH_FILENAME);
  fs.mkdirSync(dshHome, { recursive: true });
  fs.writeFileSync(overlayPath, buildPatchBody(pluginFile), "utf8");

  // `dsh web` reads the PROFILE-level user patch layer, so that is the one that
  // must carry the plugin for the running surface. We still merge the global
  // layer too, so a non-web profile that consults it also picks the plugin up.
  const profile = options.profile || DEFAULT_PROFILE;
  const profileLayer = writeProfilePatchLayer(dshHome, profile, pluginFile);
  const layer = writePatchLayer(dshHome, pluginFile, options);

  if (!options.silent) {
    console.log(`Clawd DeepSeek Harness bridge → ${overlayPath}`);
    console.log(`  profile="${profile}" layer: ${profileLayer.patchPath} (added=${profileLayer.added})`);
    if (layer.added) console.log(`  Global layer: ${layer.patchPath} (added)`);
    else if (layer.updated) console.log(`  Global layer: ${layer.patchPath} (updated)`);
    else console.log(`  Global layer: ${layer.patchPath} (already present)`);
    console.log(`  Enable with: dsh web --patch ${overlayPath}`);
  }

  return {
    status: "ok",
    added: layer.added || profileLayer.added,
    updated: layer.updated || profileLayer.updated,
    dshHome,
    profile,
    patchPath: profileLayer.patchPath,
    globalPatchPath: layer.patchPath,
    overlayPath,
    pluginFile,
  };
}

module.exports = {
  DEFAULT_PARENT_DIR: null,
  DEFAULT_CONFIG_PATH: null,
  DEFAULT_PROFILE,
  PLUGIN_DIR_NAME,
  PLUGIN_ID,
  buildPatchBody,
  stripYamlComments,
  layerHasPlugin,
  mergeIntoPatchLayer,
  registerDshBridge,
  resolveDshHome,
  resolvePluginDir,
  resolvePluginEntry,
  resolvePluginFileUrl,
  writePatchLayer,
  writeProfilePatchLayer,
};

if (require.main === module) {
  try {
    registerDshBridge({});
  } catch (err) {
    console.error(err.message);
    process.exit(1);
  }
}
