#!/usr/bin/env node
// Register Clawd's DeepSeek Harness (dsh) integration into the user's dsh
// plugin composition.
//
// dsh runs Claude Code-format COMMAND hooks through its `dsh-hooks-claude-code`
// bridge, so the "Claude Code scheme" works as-is: we ship a command hook
// script (clawd-dsh-hook.js), generate a Claude Code hooks.json that wires the
// supported events to it, and mount the bridge in the dsh profile patch layer
// pointing `configPath` at that hooks.json. The bridge then runs our hook at the
// matching moments → POST /state.
//
// Events the bridge does not run (error / notification / sleeping / sweeping)
// plus approval and user-questions are handled by the native bridge plugin
// (hooks/dsh-plugin/index.mjs), mounted here too as a `file://` plugin.
//
// This installer:
//   1. Writes hooks.json (command hooks → clawd-dsh-hook.js) to $DSH_HOME/clawd/.
//   2. Writes a ready-to-use patch overlay `$DSH_HOME/clawd-on-desk.cordis.yml`.
//   3. Merges the same `insert` into the PROFILE user patch layer
//      (`$DSH_HOME/profiles/<profile>/cordis.patch.yml`) and the GLOBAL layer.
//
// DSH HOME = $DSH_HOME, else ~/.dsh. Missing home => skipped (dsh not installed).

const fs = require("fs");
const os = require("os");
const path = require("path");
const { pathToFileURL } = require("url");
const { asarUnpackedPath } = require("./json-utils");
const { resolveNodeBin } = require("./server-config");

const PLUGIN_DIR_NAME = "dsh-plugin";
const PLUGIN_ENTRY = "index.mjs";
const PLUGIN_ID = "clawd-on-desk";
const BRIDGE_PLUGIN_ID = "dsh-hooks-claude-code";
const BRIDGE_PLUGIN_NAME = "@deepseek-ai/dsh-hooks-claude-code";
const HOOK_SCRIPT_NAME = "clawd-dsh-hook.js";
const HOOKS_FILENAME = "dsh-hooks.json";
const PATCH_FILENAME = "clawd-on-desk.cordis.yml";
const PATCH_LAYER = "cordis.patch.yml";
// `dsh web` reads the PROFILE-LEVEL user patch layer
// ($DSH_HOME/profiles/<profile>/cordis.patch.yml), not the global
// $DSH_HOME/cordis.patch.yml. The web surface's profile is named "web".
const DEFAULT_PROFILE = "web";

function resolvePluginDir(baseDir) {
  return path.resolve(baseDir || __dirname, PLUGIN_DIR_NAME);
}

function resolvePluginEntry(baseDir) {
  return path.join(resolvePluginDir(baseDir), PLUGIN_ENTRY);
}

/** file:// URL for the plugin entry — the `name` the loader imports. */
function resolvePluginFileUrl(baseDir) {
  const entry = asarUnpackedPath(resolvePluginEntry(baseDir));
  return pathToFileURL(entry).href;
}

/** Absolute path to the command hook script the dsh bridge will run. */
function resolveHookScriptPath(baseDir) {
  return asarUnpackedPath(path.resolve(baseDir || __dirname, HOOK_SCRIPT_NAME));
}

function resolveDshHome(options = {}) {
  if (options.dshHome) return options.dshHome;
  const env = options.env || process.env;
  if (env && env.DSH_HOME) return env.DSH_HOME;
  return path.join(os.homedir(), ".dsh");
}

/**
 * Build a Claude Code hooks.json that wires the bridge-supported events to the
 * command hook script. The dsh bridge runs only these command hooks; the
 * missing events are covered by the native plugin.
 */
function buildHooksJson(hookScriptPath, nodeBin) {
  const events = [
    "SessionStart", "UserPromptSubmit", "PreToolUse", "PostToolUse",
    "Stop", "SubagentStart", "SubagentStop",
  ];
  const hooks = {};
  for (const event of events) {
    hooks[event] = [{
      matcher: "",
      hooks: [{ type: "command", command: `"${nodeBin}" "${hookScriptPath}" ${event}` }],
    }];
  }
  return { hooks };
}

/** Default directory where Clawd writes the dsh hooks.json (inside $DSH_HOME/clawd). */
function hooksJsonPath(dshHome) {
  return path.join(dshHome, "clawd", HOOKS_FILENAME);
}

/** Write the hooks.json (idempotent). Returns the absolute path. */
function writeHooksJson(dshHome, hookScriptPath, nodeBin, options = {}) {
  const hooksPath = options.hooksPath || hooksJsonPath(dshHome);
  fs.mkdirSync(path.dirname(hooksPath), { recursive: true });
  fs.writeFileSync(hooksPath, JSON.stringify(buildHooksJson(hookScriptPath, nodeBin), null, 2), "utf8");
  return hooksPath;
}

/**
 * Build the patch overlay body: a list with an `insert` slice mounting BOTH
 * plugins — the dsh bridge (runs our command hooks) and our native bridge
 * plugin (supplements error/notification/sleeping/sweeping + approval +
 * user-questions).
 */
function buildPatchBody(hooksJsonPath, pluginFileUrl) {
  const bridgeName = JSON.stringify(BRIDGE_PLUGIN_NAME); // double-quoted JSON is valid YAML
  const pluginName = JSON.stringify(pluginFileUrl);
  const configPathYaml = JSON.stringify(hooksJsonPath);
  return [
    "# Generated by Clawd on Desk. Do not edit the block between the markers.",
    "# Enable with: dsh web --patch " + path.join("$DSH_HOME", PATCH_FILENAME),
    `- insert:`,
    `    - id: ${BRIDGE_PLUGIN_ID}`,
    `      name: ${bridgeName}`,
    `      config:`,
    `        configPath: ${configPathYaml}`,
    `    - id: ${PLUGIN_ID}`,
    `      name: ${pluginName}`,
    `      config:`,
    `        events: true`,
    `        approval: true`,
    ``,
  ].join("\n");
}

/** Whether the user patch layer already contains our plugin id(s). */
function layerHasPlugin(text) {
  return typeof text === "string"
    && (text.includes(`id: ${PLUGIN_ID}`) || text.includes(`id: ${BRIDGE_PLUGIN_ID}`));
}

/** Drop YAML comment lines and whitespace, leaving only structure. */
function stripYamlComments(text) {
  return String(text || "")
    .split("\n")
    .filter((line) => !/^\s*#/.test(line))
    .join("\n")
    .trim();
}

/**
 * Merge our insert slice into an existing patch-layer file. A dsh patch layer
 * is a top-level YAML list; a fresh profile layer is `[]` (often under a
 * comment header), so we must REPLACE that empty list. Handles:
 *   - empty / comment-only / `[]` → replace with our list
 *   - an existing list          → append our `- insert:` as a new item
 *   - already contains our id   → no-op
 */
function mergeIntoPatchLayer(existingText, hooksJsonPath, pluginFileUrl) {
  if (layerHasPlugin(existingText)) {
    return { text: existingText, changed: false, added: false, updated: false };
  }
  const block = buildPatchBody(hooksJsonPath, pluginFileUrl);
  const stripped = stripYamlComments(existingText);
  if (stripped === "" || stripped === "[]" || stripped === "[ ]" || stripped === "[]\n") {
    return { text: block, changed: true, added: true, updated: false };
  }
  const trimmed = (existingText || "").trimEnd();
  const text = trimmed.length > 0 ? `${trimmed}\n${block}` : block;
  return { text, changed: true, added: true, updated: false };
}

function writePatchLayer(dshHome, hooksJsonPath, pluginFileUrl, options = {}) {
  const patchPath = options.patchPath || path.join(dshHome, PATCH_LAYER);
  let existing = "";
  try {
    existing = fs.readFileSync(patchPath, "utf8");
  } catch {}
  const merged = mergeIntoPatchLayer(existing, hooksJsonPath, pluginFileUrl);
  if (merged.changed) {
    fs.mkdirSync(path.dirname(patchPath), { recursive: true });
    fs.writeFileSync(patchPath, merged.text, "utf8");
  }
  return { patchPath, changed: merged.changed, added: merged.added, updated: merged.updated };
}

/** Write the PROFILE-level user patch layer dsh actually reads (e.g. web). */
function writeProfilePatchLayer(dshHome, profile, hooksJsonPath, pluginFileUrl) {
  const patchPath = path.join(dshHome, "profiles", profile, PATCH_LAYER);
  return writePatchLayer(dshHome, hooksJsonPath, pluginFileUrl, { patchPath });
}

/**
 * Register the Clawd dsh integration (command hooks + native bridge plugin).
 *
 * @param {object} [options]
 * @param {boolean} [options.silent]    suppress console output
 * @param {string}  [options.dshHome]   override dsh home (for tests)
 * @param {string}  [options.patchPath] override user patch-layer path (for tests)
 * @param {string}  [options.hooksPath] override hooks.json path (for tests)
 * @param {string}  [options.profile]   dsh profile name (default: web)
 * @param {string}  [options.baseDir]   override hooks dir base (for tests)
 * @param {string}  [options.nodeBin]   override node binary (for tests)
 * @param {string}  [options.env]       env override (for tests)
 * @returns {{ status: string, added: boolean, updated: boolean, dshHome: string, profile: string, patchPath: string, globalPatchPath: string, hooksPath: string, pluginFile: string, overlayPath: string, reason?: string }}
 */
function registerDshBridge(options = {}) {
  const dshHome = resolveDshHome(options);
  const pluginFile = resolvePluginFileUrl(options.baseDir);
  const hookScript = resolveHookScriptPath(options.baseDir);
  const nodeBin = options.nodeBin || resolveNodeBin() || "node";

  let homeExists = true;
  if (options.forceCreate !== true) {
    try { homeExists = fs.statSync(dshHome).isDirectory(); } catch { homeExists = false; }
  }
  if (!homeExists) {
    if (!options.silent) {
      console.log(`Clawd: ${dshHome} not found — skipping DeepSeek Harness integration registration`);
    }
    return {
      status: "skipped",
      added: false,
      updated: false,
      dshHome,
      profile: options.profile || DEFAULT_PROFILE,
      patchPath: path.join(dshHome, PATCH_LAYER),
      globalPatchPath: path.join(dshHome, PATCH_LAYER),
      hooksPath: hooksJsonPath(dshHome),
      pluginFile,
      overlayPath: path.join(dshHome, PATCH_FILENAME),
      reason: "dsh-home-not-found",
    };
  }

  // 1) Write the Claude Code hooks.json the bridge will read.
  const hooksPath = writeHooksJson(dshHome, hookScript, nodeBin, options);

  // 2) Always write the standalone `--patch` overlay (idempotent).
  const overlayPath = path.join(dshHome, PATCH_FILENAME);
  fs.mkdirSync(dshHome, { recursive: true });
  fs.writeFileSync(overlayPath, buildPatchBody(hooksPath, pluginFile), "utf8");

  // 3) Merge into the PROFILE user patch layer (the one dsh web actually reads).
  //    Only touch the home-layer (global) when explicitly asked (writeGlobal: true),
  //    so we don't create a duplicate loader entry id that dsh rejects at boot.
  const profile = options.profile || DEFAULT_PROFILE;
  const profileLayer = writeProfilePatchLayer(dshHome, profile, hooksPath, pluginFile);
  const layer = options.writeGlobal
    ? writePatchLayer(dshHome, hooksPath, pluginFile, options)
    : { patchPath: path.join(dshHome, PATCH_LAYER), added: false, updated: false };

  if (!options.silent) {
    console.log(`Clawd DeepSeek Harness integration → ${overlayPath}`);
    console.log(`  hooks.json: ${hooksPath}`);
    console.log(`  profile="${profile}" layer: ${profileLayer.patchPath} (added=${profileLayer.added})`);
    if (options.writeGlobal) console.log(`  Global layer: ${layer.patchPath} (added=${layer.added}, updated=${layer.updated})`);
    console.log(`  Enable with: dsh web --patch ${overlayPath}`);
  }

  return {
    status: "ok",
    added: layer.added || profileLayer.added,
    updated: layer.updated || profileLayer.updated,
    dshHome,
    profile,
    patchPath: profileLayer.patchPath,
    globalPatchPath: layer.patchPath,
    hooksPath,
    pluginFile,
    overlayPath,
  };
}

module.exports = {
  DEFAULT_PARENT_DIR: null,
  DEFAULT_CONFIG_PATH: null,
  DEFAULT_PROFILE,
  PLUGIN_DIR_NAME,
  PLUGIN_ID,
  BRIDGE_PLUGIN_ID,
  BRIDGE_PLUGIN_NAME,
  HOOK_SCRIPT_NAME,
  HOOKS_FILENAME,
  buildHooksJson,
  buildPatchBody,
  stripYamlComments,
  layerHasPlugin,
  mergeIntoPatchLayer,
  registerDshBridge,
  resolveDshHome,
  resolveHookScriptPath,
  resolvePluginDir,
  resolvePluginEntry,
  resolvePluginFileUrl,
  hooksJsonPath,
  writeHooksJson,
  writePatchLayer,
  writeProfilePatchLayer,
};

if (require.main === module) {
  try {
    registerDshBridge({});
  } catch (err) {
    console.error(err.message);
    process.exit(1);
  }
}
