module.exports = {
  id: "mavis",
  name: "Mavis (MiniMax Code)",
  processNames: {
    win: ["MiniMax Code.exe", "mcode.exe"],
    mac: ["MiniMax Code", "MiniMax Code Helper", "mcode", "mavis"],
    linux: ["minimax-code", "mcode", "mavis"],
  },
  eventSource: "hook",
  eventMap: {
    SessionStart: "idle",
    SessionEnd: "sleeping",
    UserPromptSubmit: "thinking",
    PreToolUse: "working",
    PermissionRequest: "notification",
    PostToolUse: "working",
    PostToolUseFailure: "error",
    SubagentStart: "juggling",
    SubagentStop: "working",
    Stop: "attention",
    StopFailure: "error",
    PreCompact: "sweeping",
    PostCompact: "attention",
    Notification: "notification",
    Elicitation: "notification",
  },
  capabilities: {
    httpHook: true,
    permissionApproval: true,
    notificationHook: true,
    interactiveBubble: true,
    sessionEnd: true,
    subagent: true,
  },
  hookConfig: {
    configFormat: "minimax-plugin-json",
  },
  pidField: "mavis_pid",
};
